name: Release Prepare

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  release:
    name: Release Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 

      - name: Bump release version then push tag
        run: |
          sh release.sh ${{ github.event.inputs.version }}
